name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
